# Name of your application. Used to uniquely configure containers.
service: fakelio

# Name of the container image.
image: ghcr.io/YOUR_GITHUB_USERNAME/fakelio

# Deploy to these servers.
servers:
  web:
    - YOUR_SERVER_IP

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: fakelio.YOUR_DOMAIN.com
  app_port: 8080

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: YOUR_GITHUB_USERNAME

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

# Use a different ssh user than root
#
ssh:
  user: app

